disabled_rules:
  - line_length
  - trailing_whitespace
  - orphaned_doc_comment
  - nesting
  - function_body_length
  - function_parameter_count
  - force_try

opt_in_rules:
  - let_var_whitespace

included:
  - OOTD
excluded:
  - OOTD/Application/AppDelegate.swift
  - OOTD/Application/SceneDelegate.swift

identifier_name:
  excluded:
    - id

force_cast: warning
